environment:
  domain: "dockerlab.local"
  masterip: "10.10.10.11"
  base_box: "ubuntu/xenial64"

boxes:
- name: "nginx-1"
  role: "manager"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "1024"
  cpu: "1"

- name: "nginx-2"
  role: "worker"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1024"
  cpu: "1"

- name: "nginx-3"
  role: "worker"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "2"

- name: "nginx-4"
  role: "worker"
  mgmt_ip: "10.10.10.14"
  hostonly_ip: "192.168.56.14"
  mem: "1524"
  cpu: "2"

- name: "nginx-client"
  role: "client"
  mgmt_ip: "10.10.10.15"
  hostonly_ip: "192.168.56.15"
  mem: "1024"
  cpu: "1"

